variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  PITEST_OPTS: "-DwithHistory"

image: maven:3-openjdk-11

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == 'dev'
    - if: $CI_COMMIT_REF_NAME == 'main'

stages:
  - images
  - build
  - package
  - test-core
  - test-spark-adapter
  - e2e-spark-adapter
  - check

include:
  - local: '.gitlab/stages/images.yml'
  - local: '.gitlab/stages/build.yml'
  - local: '.gitlab/stages/package.yml'
  - local: '.gitlab/stages/test-core.yml'
  - local: '.gitlab/stages/test-spark-adapter.yml'
  - local: '.gitlab/stages/check.yml'

cache:
  paths:
    - .m2/repository
