variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

image: maven:3-openjdk-11

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == 'dev'
    - if: $CI_COMMIT_REF_NAME == 'main'

stages:
  - images
  - build
  - test
  - check

include:
  - local: '.gitlab/stages/images.yml'
  - local: '.gitlab/stages/build.yml'
  - local: '.gitlab/stages/test.yml'
  - local: '.gitlab/stages/check.yml'

cache:
  paths:
    - .m2/repository
