variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

image: maven:3-openjdk-11

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == 'dev'
    - if: $CI_COMMIT_REF_NAME == 'main'

stages:
  - build-image
  - build-core
  - build-adapters
  - tests
  - checks

include:
  - local: '.gitlab/stages/build-image.yml'
  - local: '.gitlab/stages/build-core.yml'
  - local: '.gitlab/stages/build-adapters.yml'
  - local: '.gitlab/stages/tests.yml'
  - local: '.gitlab/stages/checks.yml'

cache:
  paths:
    - .m2/repository
    - target
