variables:
  MAVEN_OPTS: -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository

image: maven:3-openjdk-11

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == 'dev'
    - if: $CI_COMMIT_REF_NAME == 'main'

stages:
  - linter
  - build
  - test

cache:
  paths:
    - .m2/repository
    - target

lint_job:
  stage: linter

  script:
    - echo "Spotless check started"
    - "mvn spotless:check"

build_job:
  stage: build

  script:
    - echo "Maven compile started"
    - "mvn clean compile"

test_job:
  stage: test

  script:
    - echo "Maven test started"
    - "mvn test"
