build:
  stage: build

  script:
    - echo "Build started"
    - "mvn process-test-classes"

  artifacts:
    name: build
    expire_in: 2 hours
    paths:
      - core/target/
      - adapter/spark/target/
