build-core:
  stage: build
  dependencies: []
  needs: []
  script:
    - echo "Build core started"
    - "mvn -pl core install -DskipTests -am"
  artifacts:
    name: build-core
    paths:
      - core/target
      - .m2/repository/com/asml/apa/wta
  cache: []

build-spark-adapter:
  stage: build
  needs: [build-core]
  dependencies:
    - build-core
  script:
    - echo "Build Spark adapter started"
    - "mvn -pl adapter/spark process-test-classes"
  artifacts:
    name: build-spark-adapter
    paths:
      - adapter/spark/target
      - .m2/repository/com/asml/apa/wta
  cache: []

package-spark-adapter-e2e:
  stage: build
  needs: [build-spark-adapter]
  dependencies:
    - build-spark-adapter
  script:
    - echo "Package Spark adapter started"
    - "mvn -pl adapter/spark jar:jar assembly:single@e2e"
  artifacts:
    name: package-spark-adapter-e2e
    paths:
      - adapter/spark/target/*-e2e.jar
