build-core:
  stage: build

  script:
    - echo "Build core started"
    - "mvn -pl core install -DskipTests"

  artifacts:
    name: build-core
    expire_in: 2 hours
    paths:
      - core/target
      - .m2/repository/com/asml/apa

build-adapters:
  stage: build

  needs: [build-core]
  dependencies:
    - build-core

  script:
    - echo "Build Spark adapter started"
    - "mvn -pl adapter/spark process-test-classes"

  artifacts:
    name: build-adapters
    expire_in: 2 hours
    paths:
      - adapter/spark/target
