build-core:
  stage: build
  dependencies: []
  needs: [build-base-image]
  script:
    - echo "Build core started"
    - "mvn -pl core install -DskipTests -am"
  artifacts:
    name: build-core
    expire_in: 20 minutes
    paths:
      - core/target
      - .m2/repository/com/asml/apa/wta
  cache:
    - key:
        prefix: test
        files:
          - pom.xml
          - core/pom.xml
      paths:
        - .m2/repository

build-spark-adapter:
  stage: build
  needs: [build-core]
  dependencies:
    - build-core
  script:
    - echo "Build Spark adapter started"
    - "mvn -pl adapter/spark process-test-classes"
  artifacts:
    name: build-spark-adapter
    expire_in: 20 minutes
    paths:
      - adapter/spark/target
      - .m2/repository/com/asml/apa/wta
  cache:
    - key:
        prefix: test
        files:
          - pom.xml
          - core/pom.xml
      paths:
        - .m2/repository

build-hadoop-connector:
  stage: build
  needs: [build-core]
  dependencies:
    - build-core
  script:
    - echo "Build Hadoop connector started"
    - "mvn -pl connector/hdfs process-test-classes"
  artifacts:
    name: build-hadoop-connector
    expire_in: 20 minutes
    paths:
      - connector/hadoop/target
      - .m2/repository/com/asml/apa/wta
  cache:
    - key:
        prefix: test
        files:
          - pom.xml
          - core/pom.xml
      paths:
        - .m2/repository


package-spark-adapter-e2e_2.12:
  stage: build
  needs: [build-spark-adapter]
  dependencies:
    - build-spark-adapter
  script:
    - echo "Package Spark adapter for Scala 2.12 started"
    - "mvn -pl adapter/spark -De2e=true jar:jar assembly:single"
  artifacts:
    name: package-spark-adapter-e2e_2.12
    expire_in: 20 minutes
    paths:
      - adapter/spark/target/*-e2e.jar
  cache:
    - key:
        prefix: test
        files:
          - pom.xml
          - core/pom.xml
      paths:
        - .m2/repository

package-spark-adapter-e2e_2.13:
  stage: build
  needs: [build-core]
  dependencies:
    - build-core
  script:
    - echo "Package Spark adapter for Scala 2.13 started"
    - "mvn -pl adapter/spark -Dspark.scala.version=2.13 -De2e=true process-test-classes jar:jar assembly:single"
  artifacts:
    name: package-spark-adapter-e2e_2.13
    expire_in: 20 minutes
    paths:
      - adapter/spark/target/*-e2e.jar
  cache:
    - key:
        prefix: test
        files:
          - pom.xml
          - core/pom.xml
      paths:
        - .m2/repository
