build-core:
  stage: build
  dependencies: []
  needs: []
  script:
    - echo "Build core started"
    - "mvn -pl core install -DskipTests -am"
  artifacts:
    name: build-core
    expire_in: 20 minutes
    paths:
      - core/target
      - .m2/repository/com/asml/apa/wta
  cache: []

build-spark-adapter:
  stage: build
  needs: [build-core]
  dependencies:
    - build-core
  script:
    - echo "Build Spark adapter started"
    - "mvn -pl adapter/spark process-test-classes"
  artifacts:
    name: build-spark-adapter
    expire_in: 20 minutes
    paths:
      - adapter/spark/target
      - .m2/repository/com/asml/apa/wta
  cache: []

package-spark-adapter-e2e_2.12:
  stage: build
  needs: [build-spark-adapter]
  dependencies:
    - build-spark-adapter
  script:
    - echo "Package Spark adapter for Scala 2.12 started"
    - "mvn -pl adapter/spark jar:jar assembly:single@e2e"
  artifacts:
    name: package-spark-adapter-e2e_2.12
    expire_in: 20 minutes
    paths:
      - adapter/spark/target/*-e2e.jar

package-spark-adapter-e2e_2.13:
  stage: build
  needs: [build-core]
  dependencies:
    - build-core
  script:
    - echo "Package Spark adapter for Scala 2.13 started"
    - "mvn -pl adapter/spark -Dspark.scala.version=2.13 process-classes jar:jar assembly:single@e2e"
  artifacts:
    name: package-spark-adapter-e2e_2.13
    expire_in: 20 minutes
    paths:
      - adapter/spark/target/*-e2e.jar
